// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;

namespace MonoMedicalIOS
{
	public partial class CustomProviderCell : UITableViewCell
	{
		public CustomProviderCell (IntPtr handle) : base (handle)
		{
		}

		public CustomProviderCell (string cellIdentifier):base(UITableViewCellStyle.Default, cellIdentifier)
		{
			
		}

		public void BindFields(MedicalProvider mp){
			this.ProviderName.Text=mp.FirstName + " " + mp.LastName;
			this.ProviderAddress.Text = mp.Address;
			this.ProviderCityState.Text = mp.City + ", " + mp.State + "     "+mp.ZipCode;
		}
	}
}
