// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;

namespace MonoMedicalIOS
{
	public partial class MedProviderCell : UITableViewCell
	{


		public MedProviderCell (NSString cellId) : base (UITableViewCellStyle.Default, cellId)
		{
			
		}

		public void SetCellProperties(MedicalProvider mp){
			this.lblAddress.Text = mp.Address;
			this.lblProviderName.Text = mp.FirstName + " " + mp.LastName;
			this.CityStateZip.Text = mp.City+", " + mp.State+"     "+ mp.ZipCode;
		}
	}
}
