// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MonoMedicalIOS
{
	public partial class Home : UIViewController
	{
		public Home (IntPtr handle) : base (handle)
		{
		}
	}
}
