// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;

namespace MonoMedicalIOS
{

	public partial class CitiesTableController : UIViewController,AppModelInterface
	{

		private ITableViewSelectedItem tableSource;

		#region AppModelInterface implementation
		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}

		#endregion

		public CitiesTableController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if(AppModel!=null){
				this.citiesTable.Source= new TableSource(AppModel.Cities.ToArray());
				tableSource =(ITableViewSelectedItem) this.citiesTable.Source;
			}
		}

		partial void SelectionMade (NSObject sender)
		{
			AppModel.ProviderSearchCriteria.City=tableSource.SelectedText;
			DismissViewController(true,null);
		}
		partial void CancelCities (NSObject sender)
		{
			DismissViewController(true,null);
		}
	}
}
