// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MonoMedicalIOS
{
	public class CitiesSource : UITableViewDataSource {
		protected string[] tableItems;
		protected string cellIdentifier = "TableCell";
		public CitiesSource (string[] items)
		{
			tableItems = items;
		}
		public override int RowsInSection (UITableView tableview, int section)
		{
			return tableItems.Length;
		}
		public override UITableViewCell GetCell (UITableView tableView, MonoTouch.Foundation.NSIndexPath indexPath)
		{
			// request a recycled cell to save memory
			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
			// if there are no cells to reuse, create a new one
			if (cell == null)
				cell = new UITableViewCell (UITableViewCellStyle.Default, cellIdentifier);
			cell.TextLabel.Text = tableItems[indexPath.Row];
			return cell;
		}
	}

	public partial class CitiesTableController : UIViewController,AppModelInterface
	{
		#region AppModelInterface implementation

		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}

		#endregion

		public CitiesTableController (IntPtr handle) : base (handle)
		{
		}

		partial void CancelCities (NSObject sender)
		{
			DismissViewController(true,null);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if(AppModel!=null){
				this.citiesTable.DataSource= new CitiesSource(AppModel.Cities.ToArray());
			}
		}
	}
}
