// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;

namespace MonoMedicalIOS
{
	public partial class Home : UIViewController,AppModelInterface
	{
		public ViewModel AppModel {
			get;
			set;
		}

		public Home (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		
		}
	}
}
