// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MonoMedicalIOS
{
	public partial class InfoController : UIViewController,AppModelInterface
	{
		#region AppModelInterface implementation
		
		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}
		
		#endregion

		public InfoController (IntPtr handle) : base (handle)
		{
		}
	}
}
