// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;
using System.Collections.Generic;
using System.Drawing;


namespace MonoMedicalIOS
{
	public partial class MedProviderTableController : UIViewController, AppModelInterface
	{
		//private ITableViewSelectedProvider tableSource;
		private ProviderTableSource dataSource;
		private LoadingOverlay loadingOverlay;

		#region AppModelInterface implementation
		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}
		
		#endregion

		public MedProviderTableController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if(AppModel!=null){
				loadingOverlay = new LoadingOverlay (UIScreen.MainScreen.Bounds);
				View.Add (loadingOverlay);

				dataSource = new ProviderTableSource(){ AppModel=this.AppModel};
				this.MedProviderTable.Source= dataSource;
				AppModel.ProviderSearchCompleted+=(e,a)=>{
					this.BeginInvokeOnMainThread(delegate {
						//dataSource.ProviderList = AppModel.ProviderResults.ToArray();
						this.MedProviderTable.ReloadData();
						loadingOverlay.Hide ();
					});
				};
				AppModel.SearchForProviders();
			}
		}


		partial void CancelItem (MonoTouch.Foundation.NSObject sender){
			DismissViewController(true,null);
		}
	}

}
