// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using CommonLogic;
namespace MonoMedicalIOS
{
	public partial class MedProviderTableController : UIViewController, AppModelInterface
	{
		private ITableViewSelectedProvider tableSource;

		#region AppModelInterface implementation
		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}
		
		#endregion

		public MedProviderTableController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			if(AppModel!=null){
				AppModel.ProviderSearchCompleted+=(e,a)=>{
					this.BeginInvokeOnMainThread(delegate {
						this.MedProviderTable.Source= new ProviderTableSource(AppModel.ProviderResults.ToArray());
						tableSource =(ITableViewSelectedProvider) this.MedProviderTable.Source;
					});
				};
				AppModel.SearchForProviders();
			}
		}


		partial void CancelItem (MonoTouch.Foundation.NSObject sender){
			DismissViewController(true,null);
		}
	}
}
