// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Linq;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using FlyoutNavigation;
using MonoTouch.Dialog;
using CommonLogic;
using System.Drawing;

namespace MonoMedicalIOS
{

	public partial class Search : UIViewController,AppModelInterface
	{
		public ViewModel AppModel {
			get;
			set;
		}

		public Search (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();




		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			var contoller = segue.DestinationViewController as AppModelInterface;
			contoller.AppModel=this.AppModel;
		}
	
	}
}
