// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Linq;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using FlyoutNavigation;
using MonoTouch.Dialog;
using CommonLogic;
using System.Drawing;

namespace MonoMedicalIOS
{

	public partial class Search : UIViewController,AppModelInterface
	{
		public ViewModel AppModel {
			get;
			set;
		}

		public Search (IntPtr handle) : base (handle)
		{
		
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.txtCity.EditingDidEnd+=delegate(object sender, EventArgs e) {
				AppModel.ProviderSearchCriteria.City=txtCity.Text;
			};
			this.txtSpecialty.EditingDidEnd+=delegate(object sender, EventArgs e) {
				AppModel.ProviderSearchCriteria.Specialty=txtSpecialty.Text;
			};
			this.txtProviderName.EditingDidEnd+=delegate(object sender, EventArgs e) {
				AppModel.ProviderSearchCriteria.Name=txtProviderName.Text;
			};

			AppModel.ProviderSearchCriteria.PropertyChanged+=(sender,args)=>{
				switch(args.PropertyName){
					case "City":
						txtCity.Text=AppModel.ProviderSearchCriteria.City;
						break;
					case "Specialty":
						txtSpecialty.Text=AppModel.ProviderSearchCriteria.Specialty;
						break;
				}
			
			};
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			AppModel.ProviderSearchCriteria.Name=txtProviderName.Text;
			var controller = segue.DestinationViewController as AppModelInterface;
			controller.AppModel=this.AppModel;
		}

		public override void TouchesBegan (NSSet touches, UIEvent evt)
		{
			base.TouchesBegan (touches, evt);
			this.View.EndEditing(true);
		}


	
	}
}
