// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MonoMedicalIOS
{
	public partial class SpecialtiesTableController : UITableViewController,AppModelInterface
	{
		#region AppModelInterface implementation

		public CommonLogic.ViewModel AppModel {
			get;
			set;
		}

		#endregion

		public SpecialtiesTableController (IntPtr handle) : base (handle)
		{
		}
	}
}
